  version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip freeze > requirements.lock
      - save_cache:
          key: v1-pip-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Run tests
          command: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-{{ checksum "requirements.txt" }}
      - run:
          name: Install black
          command: pip install black
      - run:
          name: Check code style
          command: black --check .

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - lint